"""Robot voice control tools collection."""

from tools.robot_actions import (
    robot_stand,
    robot_squat,
    robot_squat_up,
    robot_go_forward,
    robot_back_fast,
    robot_left_move_fast,
    robot_right_move_fast,
    robot_dance_one,
    robot_dance_two,
    drone_takeoff,
    drone_land,
    drone_move_up,
    drone_move_down,
    drone_move_left,
    drone_move_right,
    drone_move_forward,
    drone_move_back,
    dog_stand_up,
    dog_lay_down,
    dog_move_forward,
    dog_move_backward,
    dog_move_left,
    dog_move_right,
    dog_stop,
)


def get_all_tools() -> list:
    """Return a list of all registered robot control tools."""
    return [
        robot_stand,
        robot_squat,
        robot_squat_up,
        robot_go_forward,
        robot_back_fast,
        robot_left_move_fast,
        robot_right_move_fast,
        robot_dance_one,
        robot_dance_two,
        drone_takeoff,
        drone_land,
        drone_move_up,
        drone_move_down,
        drone_move_left,
        drone_move_right,
        drone_move_forward,
        drone_move_back,
        dog_stand_up,
        dog_lay_down,
        dog_move_forward,
        dog_move_backward,
        dog_move_left,
        dog_move_right,
        dog_stop,
    ]


__all__ = [
    "robot_stand",
    "robot_squat",
    "robot_squat_up",
    "robot_go_forward",
    "robot_back_fast",
    "robot_left_move_fast",
    "robot_right_move_fast",
    "robot_dance_one",
    "robot_dance_two",
    "drone_takeoff",
    "drone_land",
    "drone_move_up",
    "drone_move_down",
    "drone_move_left",
    "drone_move_right",
    "drone_move_forward",
    "drone_move_back",
    "dog_stand_up",
    "dog_lay_down",
    "dog_move_forward",
    "dog_move_backward",
    "dog_move_left",
    "dog_move_right",
    "dog_stop",
    "get_all_tools",
]
